apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: # Please don't use plain text -> use base64 encoded instead.
  mongo-root-username: bW9uZ28tdXNlcg==
  mongo-root-password: bW9uZ28tcGFzc3dvcmQ=
